version: 2
jobs:
  build:

    working_directory: ~/quantal-auth

    docker:
      - mage: webpackcontrib/circleci-node8

    steps:

      - checkout

      - restore_cache:
          key: quantal-auth-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mkdir -p /var/log
      - run: sudo touch /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json && sudo chmod 777 /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json

      - save_cache:
          paths:
            - ~/.m2
          key: base_pom-{{ checksum "pom.xml" }}

      - run: mvn package

      - run: mvn deploy -Pgpg -s settings.xml


      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/base-pom-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build_test_and_deploy_project:
    jobs:
      - build
